// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uoimyivzenwwgbngbjuq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvaW15aXZ6ZW53d2dibmdianVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MzgwNTgsImV4cCI6MjA2NDExNDA1OH0.BUbINHGJLq_nApbLrLEDbKljUvPY7WudD7lsYH4_NRA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);